"""
generate_visuals_exp2.py

This script generates visualizations for Experiment 2 (Trade-offs in Anomaly Detection Resiliency and 
Privacy Exposure vs Governance Overhead). It processes the JSON results generated by the experiment 
and produces two figures:
1. A bar chart showcasing the role-wise False Positive rates.
2. A dual-axis chart demonstrating the trade-offs between PHI exposure and reviewer overhead.
"""

import json
import os
import matplotlib.pyplot as plt
import numpy as np

def set_grayscale_style():
    """
    Applies a grayscale color palette and sets the font family for publication-quality figures.
    """
    plt.rcParams["axes.prop_cycle"] = plt.cycler(
        color=["#000000", "#555555", "#888888", "#AAAAAA"]
    )
    plt.rcParams["font.family"] = "sans-serif"

def main():
    """
    Main function to read experiment results and generate visualizations.
    """
    # Apply publication style and ensure output directory exists
    set_grayscale_style()
    os.makedirs("figures", exist_ok=True)
    
    # Load the results generated by Experiment 2
    with open("results/results_exp2_advanced.json", "r") as f:
        data = json.load(f)
        
    # =========================================================================
    # Plot 1: Role-wise False Positive Rate
    # =========================================================================
    role_data = data["role_fp_rates"]
    roles = list(role_data.keys())
    
    # Capitalize role names for better display aesthetics
    display_roles = [r.replace("_", " ").title() for r in roles]
    
    # Extract mean and standard deviation (convert to percentages)
    fp_means = [role_data[r]["mean"] * 100 for r in roles]
    fp_stds = [role_data[r]["std"] * 100 for r in roles]
    
    # Calculate asymmetric error bounds to prevent error bars from dipping below 0
    lower_errors = [min(m, s) for m, s in zip(fp_means, fp_stds)]
    upper_errors = fp_stds
    asym_yerr = [lower_errors, upper_errors]
    
    plt.figure(figsize=(9, 6))
    x_pos = np.arange(len(roles))
    
    # Render the bar chart with error bars
    plt.bar(x_pos, fp_means, yerr=asym_yerr, color='#777777', edgecolor='black', capsize=5, alpha=0.9)
    plt.xticks(x_pos, display_roles, rotation=25, ha='right', fontweight='bold')
    plt.ylabel('False Positive Rate (%)', fontweight='bold')
    plt.title('Anomaly Detection Resilience across Clinical Roles', fontweight='bold', fontsize=14)
    
    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.savefig("figures/exp2_role_fp.png", dpi=300)
    plt.close()
    
    # =========================================================================
    # Plot 2: Workflow Trade-offs (Exposure vs Reviewer Minutes)
    # =========================================================================
    workflows = data["workflows"]
    labels = ["Plaintext (A)", "Unbounded Meta (B)", "Proposed"]
    w_keys = ["Baseline_A_Plaintext", "Baseline_B_Unbounded", "Proposed"]
    
    # Extract exposure metrics
    exposure_means = [workflows[k]["exposure"]["mean"] for k in w_keys]
    exposure_stds = [workflows[k]["exposure"]["std"] for k in w_keys]
    
    # Convert review minutes to Reviewer Hours
    rev_means = [workflows[k]["rev_minutes"]["mean"] / 60 for k in w_keys] 
    rev_stds = [workflows[k]["rev_minutes"]["std"] / 60 for k in w_keys]
    
    fig, ax1 = plt.subplots(figsize=(10, 6))
    x_pos = np.arange(len(labels))
    width = 0.35
    
    color_bar = "#666666"
    color_line = "#222222"
    
    # Primary Y-axis: PHI-bearing Log Records Scanned
    ax1.set_ylabel('PHI-bearing Log Records Scanned', color=color_bar, fontweight='bold')
    ax1.bar(x_pos, exposure_means, width=width, yerr=exposure_stds, capsize=5, color=color_bar, edgecolor='black', label="Scanned Log Records")
    ax1.tick_params(axis='y', labelcolor=color_bar)
    
    # Annotate bar values
    for i, v in enumerate(exposure_means):
        ax1.text(x_pos[i], v + (exposure_stds[i] if exposure_stds[i] else 0) + 5000, f"{int(v/1000)}k", ha='center', va='bottom', fontweight='bold')

    # Twin Secondary Y-axis: Analyst & Board Review Hours
    ax2 = ax1.twinx()
    ax2.set_ylabel('Analyst & Board Review Effort (Hours)', color=color_line, fontweight='bold')
    ax2.errorbar(x_pos, rev_means, yerr=rev_stds, color=color_line, marker='s', markersize=10, linewidth=2, linestyle='dotted', capsize=5, label="Review Hours")
    ax2.tick_params(axis='y', labelcolor=color_line)
    
    # Annotate line graph values
    for i, v in enumerate(rev_means):
        ax2.text(x_pos[i] + 0.1, v, f"{int(v)}h", ha='left', va='center', fontweight='bold', color=color_line)
        
    plt.xticks(x_pos, labels)
    plt.title('Trade-off: PHI Exposure Reduction vs Governance Overhead', fontsize=14, fontweight='bold')
    fig.tight_layout()
    plt.savefig("figures/exp2_tradeoff.png", dpi=300)
    plt.close()
    
    print("Exp2 Visuals generated successfully in figures/")

if __name__ == "__main__":
    main()
