"""
generate_visuals_exp3.py

This script generates visualizations and a LaTeX summary table for Experiment 3 
(End-to-End Evidentiary Overhead & Tamper Detection). It processes the JSON results 
produced by the experiment and creates:
1. A stacked bar chart visualizing the End-to-End latency components across different scales.
2. A LaTeX-formatted table summarizing End-to-End Latency, Storage Bloat, and Detections.
"""

import json
import os
import matplotlib.pyplot as plt
import numpy as np

def set_grayscale_style():
    """
    Applies a grayscale color palette and sets the font family for publication-quality figures.
    """
    plt.rcParams["axes.prop_cycle"] = plt.cycler(
        color=["#222222", "#666666", "#999999", "#CCCCCC"]
    )
    plt.rcParams["font.family"] = "sans-serif"

def main():
    """
    Main function to parse experiment 3 results, plot latencies, and output the LaTeX table.
    """
    # Apply publication style and ensure output directory exists
    set_grayscale_style()
    os.makedirs("figures", exist_ok=True)
    
    # Load the results generated by Experiment 3
    with open("results/results_exp3.json", "r") as f:
        data = json.load(f)
        
    exp3 = data
    batches = list(exp3["batches"].keys())
    labels_3 = [f"{b} events" for b in batches]
    models = ["Baseline", "ObjectHash", "CustodyChain", "FullWorkflow"]

    # =========================================================================
    # Plot: Stacked Bar Chart for End-to-End Latency
    # =========================================================================
    # For each batch size, we group the 4 models side-by-side.
    x = np.arange(len(batches))
    width = 0.2
    offsets = [-width*1.5, -width/2, width/2, width*1.5]
    
    fig, ax1 = plt.subplots(figsize=(12, 7))
    
    # Define color scheme and latency components to be stacked
    components = ["ingest_latency_ms", "pkg_generation_ms", "verify_handoff_ms", "audit_replay_ms"]
    comp_labels = ["Ingest", "Pkg Gen", "Handoff Verify", "Audit Replay"]
    comp_colors = ["#BBBBBB", "#777777", "#444444", "#111111"]
    
    # Iterate over models to plot grouped stacked bars
    for i, model in enumerate(models):
        bottoms = np.zeros(len(batches))
        
        # Plot each latency component stacked for the given model
        for c_idx, comp in enumerate(components):
            values = [exp3["batches"][b][model][comp] for b in batches]
            # Add label only for the first model to prevent duplicate legend entries
            label = comp_labels[c_idx] if i == 0 else ""
            ax1.bar(
                x + offsets[i], 
                values, 
                width, 
                bottom=bottoms, 
                label=label, 
                color=comp_colors[c_idx], 
                edgecolor="black"
            )
            bottoms += np.array(values)
            
        # Annotate the total bar height
        for j, tot in enumerate(bottoms):
            ax1.annotate(
                f"{tot:.1f}",
                xy=(x[j] + offsets[i], tot),
                xytext=(0, 2),
                textcoords="offset points",
                ha="center",
                va="bottom",
                fontsize=8,
                fontweight="bold",
                rotation=45
            )

    ax1.set_ylabel("End-to-End Latency (ms)", fontweight="bold")
    ax1.set_title("End-to-End Processing Latency by Batch Size", fontweight="bold", fontsize=14)
    ax1.set_xticks(x)
    ax1.set_xticklabels(labels_3, fontweight="bold")
    
    # Add textual labels below the bars to easily identify the models
    for b_idx in range(len(batches)):
        for i, model in enumerate(models):
            ax1.text(x[b_idx] + offsets[i], -ax1.get_ylim()[1]*0.05,
                     ["Base", "Hash", "Chain", "Full"][i],
                     ha="center", va="top", fontsize=9, rotation=45)

    ax1.legend(loc='upper left')

    plt.grid(axis='y', linestyle='--', alpha=0.5)
    plt.tight_layout()
    plt.savefig("figures/exp3_integrity_latency.png", dpi=300)
    plt.close()

    print("Exp3 Visuals generated successfully in figures/")
    
    # =========================================================================
    # LaTeX Table Generation
    # =========================================================================
    print("\n" + "="*60)
    print("COPY/PASTE THE FOLLOWING LATEX TABLE INTO YOUR MANUSCRIPT:")
    print("="*60)
    print("\\begin{table*}")
    print("\\centering")
    print("\\caption{End-to-End Evidentiary Overhead and Tamper Detection (Exp3).}")
    print("\\label{tab:5}")
    print("\\footnotesize")
    print("\\setlength{\\tabcolsep}{5pt}")
    print("\\renewcommand{\\arraystretch}{1.12}")
    print("\\begin{tabularx}{\\textwidth}{@{}l l l l c c@{}}")
    print("\\toprule")
    print("\\textbf{Batch size} & \\textbf{Architecture} & \\textbf{E2E Latency (ms)} & \\textbf{Storage Bloat (\\%)} & \\textbf{Audit Detections} & \\textbf{Handoff Detections} \\\\")
    
    for b in batches:
        print("\\midrule")
        for i, model in enumerate(models):
            res = exp3["batches"][b][model]
            e2e = res["ingest_latency_ms"] + res["pkg_generation_ms"] + res["verify_handoff_ms"] + res["audit_replay_ms"]
            b_label = f"{int(b):,}" if i == 0 else ""
            print(f"{b_label} & {model} & {e2e:.2f} & {res['storage_bloat_pct']:.1f} & {res['audit_detection_summary']} & {res['handoff_detection_summary']} \\\\")
            
    print("\\bottomrule")
    print("\\end{tabularx}")
    print("\\end{table*}")
    print("="*60 + "\n")

if __name__ == "__main__":
    main()
